version: '3'
services:
  ranchers:
    image: rancher/rancher:v2.7.9
    container_name: rancher-center
    network_mode: host
    privileged: true
    volumes:
      - ./lib/rancher/:/var/lib/rancher
      - ./lib/certs:/var/lib/ca-certificates
    restart: unless-stopped