#!/bin/bash

echo Install docker ...
curl https://releases.rancher.com/install-docker/23.0.3.sh | sh
echo Install docker compose ...
apt apt docker-compose | yes
echo set net bridge ...
net.bridge.bridge-nf-call-iptables=1
echo Install kubectl ...
snap install kubectl --classic
