#!/bin/bash

echo Install docker ...
curl https://releases.rancher.com/install-docker/23.0.3.sh | sh
echo Install docker compose ...
apt apt docker-compose | y
echo set net bridge ...
sysctl net.bridge.bridge-nf-call-iptables
echo Install kubectl ...
snap install kubectl --classic
